### ISSUE TITLE
Issue in Quizzes page.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#49]
In the Quizzes page of Soil Mechanic Labs experiments 1-4,6,7; When we click on the "Grade me" button with out answering any question the page is redirecting to the results page. Where as in such case a pop-up box with a message "Select the answers and then click on Grade me button" kind of error message should be appear.

**Comment by khushpreet-kaur** [comment]
'Grade Me` page doesn't directly show answer list, user again has to `View solutions` button to see correct answer list.  This designed was already discussed. This is to,  if user don't want to attempt any question, he/she can proceed for further solution rather than bounding or restricting them to the same page.

**Comment by BSravanthi** [comment]
Closed the issue as the lab is ported to open edx and the issues related to vlabs page are no longer considered.
